version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY_FINGERPRINT}"
      - run:
          name: Install SSH client and dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y openssh-client rsync
      - run:
          name: Setup SSH and deploy
          command: |
            ssh -o StrictHostKeyChecking=no $USER@$HOST '
                sudo rm -rf /var/www/html/*
                sudo mv /tmp/dist/* /var/www/html/
                sudo systemctl restart nginx
              '
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
