version: 2.1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build
          filters:
            branches:
              only: main            
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main

jobs:
  build:
    docker:
      - image: node:18
    steps:
      - checkout
      - run:
          name: Install dependencies and build
          command: |
            npm install
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  test:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y curl
      - run:
          name: Run tests
          command: |
            chmod +x ./test.sh
            ./test.sh

  deploy:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "SHA256:Mt4n2jKNOdmu7DApBBiVMJY48eTMmlRj2DMp6xlPdwU."
      - run:
          name: Deploy to server
          command: |
            scp -o StrictHostKeyChecking=no -r dist/* $USER@$HOST:/root/dist/
            ssh -o StrictHostKeyChecking=no $USER@$HOST "
              sudo cp -r /root/dist/* /var/www/html
              sudo systemctl restart nginx
            "
            rm ssh_key.pem
