version: 2.1

jobs:
  deploy:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install SSH client and dependencies
          command: |
            apt-get update
            apt-get install -y openssh-client rsync              
      - run:
          name: Setup SSH
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan $HOST >> ~/.ssh/known_hosts        
      - run:
          name: Deploy to server
          command: |
            rsync -avz -e "ssh -o StrictHostKeyChecking=no" dist/ $USER@$HOST:/tmp/dist/
            ssh -o StrictHostKeyChecking=no $USER@$HOST '
              sudo rm -rf /var/www/html/*
              sudo mv /tmp/dist/* /var/www/html/
              sudo systemctl restart nginx
            '

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
