version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY_FINGERPRINT}"
      - run:
          name: Install SSH client and dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y openssh-client rsync
      - run:
          name: Setup SSH and deploy
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
            echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
            chmod 700 ~/.ssh
            chmod 600 ~/.ssh/known_hosts
            
            # Debug: List contents of .ssh directory
            ls -la ~/.ssh
            
            # Start ssh-agent and add key
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/id_rsa
            
            # Debug: Print SSH key information
            ssh-add -l
            
            # Debug: Try to connect with verbose output
            ssh -vvv -o StrictHostKeyChecking=no -o ConnectTimeout=10 $USER@$HOST 'echo "SSH connection successful"'
            
            # Attempt rsync with verbose output
            if rsync -avvz -e "ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10" dist/ $USER@$HOST:/tmp/dist/; then
              ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 $USER@$HOST '
                sudo rm -rf /var/www/html/*
                sudo mv /tmp/dist/* /var/www/html/
                sudo systemctl restart nginx
              '
            else
              echo "Failed to rsync files to the server"
              exit 1
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
