version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY_FINGERPRINT}"
      - run:
          name: Install SSH client and dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y rsync            
      - run:
          name: Deploy to server
          command: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan $HOST >> ~/.ssh/known_hosts
            ssh $USER@$HOST '
              sudo systemctl restart nginx
            '

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
