version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY_FINGERPRINT}"
      - run:
          name: Install SSH client and dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y openssh-client rsync            
      - run:
          name: Deploy to server
          command: |
            ssh-keyscan $HOST >> ~/.ssh/known_hosts
            rsync -avz -e "ssh -o StrictHostKeyChecking=no" dist/ $USER@$HOST:/tmp/dist/
            ssh $USER@$HOST '
              sudo rm -rf /var/www/html/*
              sudo mv /tmp/dist/* /var/www/html/
              sudo systemctl restart nginx
            '

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
